# -*- coding: utf-8 -*-
"""idspbl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1am5cIwefsDvc202NKDoVtFzM0Rpvy7Th
"""

from google.colab import files
uploaded = files.upload()

 # Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


# Load dataset
df = pd.read_excel("/content/student_social_media_analysis_101.xlsx")

# Display first 5 rows
df.head()

# ==============================
# DATA PREPROCESSING
# ==============================

# Remove non-relevant column (if exists)
if "Student_ID" in df.columns:
    df = df.drop(columns=["Student_ID"])

# Keep only numeric columns
df_numeric = df.select_dtypes(include=['number'])

print("Cleaned Dataset:\n")
print(df_numeric.head())

# ==============================
# STATISTICAL ANALYSIS
# ==============================

print("\n--- Statistical Summary ---")
print(df_numeric.describe())

print("\n--- Mean Values ---")
print(df_numeric.mean())

print("\n--- Median Values ---")
print(df_numeric.median())

print("\n--- Standard Deviation ---")
print(df_numeric.std())

print("\n--- Minimum Values ---")
print(df_numeric.min())

print("\n--- Maximum Values ---")
print(df_numeric.max())

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Fill missing values (if any)
df.fillna(df.mean(numeric_only=True), inplace=True)

# Data types
print("\nData Types:")
print(df.dtypes)

# Group by country
country_analysis = df.groupby('Country').agg({
    'Avg_Daily_Usage_Hours': 'mean',
    'Addicted_Score': 'mean',
    'Mental_Health_Score': 'mean'
})

# Sort by addiction score
country_analysis = country_analysis.sort_values(by='Addicted_Score')

print("\nCountry-wise Analysis:")
print(country_analysis)

# Create Risk Score (custom metric)
df['Risk_Score'] = (
    df['Avg_Daily_Usage_Hours'] * 0.4 +
    df['Addicted_Score'] * 0.3 +
    (10 - df['Mental_Health_Score']) * 0.3
)

# Country-wise risk
risk_country = df.groupby('Country')['Risk_Score'].mean().sort_values()

print("\nRisk Score by Country:")
print(risk_country)

import matplotlib.pyplot as plt

# Sort data (important for clean look)
country_analysis = country_analysis.sort_values(by='Addicted_Score', ascending=False)

plt.figure(figsize=(6,6))

bars = plt.bar(
    country_analysis.index,
    country_analysis['Addicted_Score']
)

# Titles
plt.title("Country-wise Addiction Score Comparison", fontsize=14)
plt.xlabel("Country")
plt.ylabel("Addiction Score")

# Rotate labels for readability
plt.xticks(rotation=30)

# Grid for better clarity
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Add value labels on top of bars (VERY IMPORTANT)
for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width()/2,
        height,
        f'{height:.2f}',
        ha='center',
        va='bottom',
        fontsize=9
    )

plt.tight_layout()
plt.show()

# Create age groups
bins = [15, 18, 21, 25, 30]
labels = ['Teen', 'Young Adult', 'Adult', 'Mature']

df['Age_Group'] = pd.cut(df['Age'], bins=bins, labels=labels)

# Group analysis
age_analysis = df.groupby('Age_Group').agg({
    'Avg_Daily_Usage_Hours': 'mean',
    'Addicted_Score': 'mean',
    'Mental_Health_Score': 'mean'
})

print("\nAge Group Analysis:")
print(age_analysis)

# Count number of people in each age group
age_counts = df['Age_Group'].value_counts()

# Plot pie chart
plt.figure()

plt.pie(
    age_counts,
    labels=age_counts.index,
    autopct='%1.1f%%',
    startangle=90
)

plt.title("Overall Age Group Distribution")
plt.show()

age_analysis['Addicted_Score'].plot(
    kind='pie',
    autopct='%1.1f%%',
    figsize=(6,6)
)

plt.title("Addiction Score by Age Group")
plt.ylabel("")
plt.show()

age_analysis['Mental_Health_Score'].plot(
    kind='pie',
    autopct='%1.1f%%',
    figsize=(6,6)
)

plt.title("Mental Health Score by Age Group")
plt.ylabel("")
plt.show()

# ==============================
# LINE GRAPH - Average Usage by Age
# ==============================

age_usage = df.groupby('Age')['Avg_Daily_Usage_Hours'].mean()

plt.figure(figsize=(8,5))

plt.plot(
    age_usage.index,
    age_usage.values,
    marker='o',
    linewidth=2
)

plt.title("Average Daily Social Media Usage by Age")
plt.xlabel("Age")
plt.ylabel("Average Usage Hours")
plt.grid(True)

plt.show()

# ==============================
# SCATTER PLOT
# ==============================

plt.figure(figsize=(8,5))

plt.scatter(
    df['Avg_Daily_Usage_Hours'],
    df['Mental_Health_Score']
)

plt.title("Average Usage Hours vs Mental Health Score")
plt.xlabel("Average Daily Usage Hours")
plt.ylabel("Mental Health Score")

plt.grid(True)

plt.show()

# Categorize usage level
df['Usage_Level'] = pd.cut(
    df['Avg_Daily_Usage_Hours'],
    bins=[0, 3, 6, 10],
    labels=['Low', 'Medium', 'High']
)

# Show counts
print("\nUsage Level Distribution:")
print(df['Usage_Level'].value_counts())

high_risk = df[
    (df['Avg_Daily_Usage_Hours'] > 6) &
    (df['Mental_Health_Score'] < 5)
]

print("\n🚨 High Risk Students:")
print(high_risk[['Country', 'Age', 'Avg_Daily_Usage_Hours', 'Mental_Health_Score']])

print("="*50)
print("        IDEAL STUDENT HEALTH GUIDELINES")
print("="*50)

print("\n1. Screen Time Recommendation:")
print("   - Optimal Usage: 2 to 3 hours per day")
print("   - Rationale: Minimizes digital fatigue and addiction risk")

print("\n2. Sleep Recommendation:")
print("   - Ideal Duration: 7 to 8 hours per night")
print("   - Minimum Requirement: 6 hours")
print("   - Rationale: Supports cognitive function and mental stability")

print("\n3. Mental Health Benchmark:")
print("   - Desired Score: 8 to 10 (on a scale of 1–10)")
print("   - Interpretation: Indicates good psychological well-being")

print("\nConclusion:")
print("Maintaining balanced screen time along with adequate sleep")
print("contributes significantly to better mental health outcomes.")

print("="*50)
ideal_students = df[
    (df['Avg_Daily_Usage_Hours'] <= 3) &
    (df['Sleep_Hours_Per_Night'] >= 6) &
    (df['Mental_Health_Score'] >= 8)
]

print("Number of Ideal Healthy Students:", len(ideal_students))
ideal = ideal_students.head()

print("Ideal Students:")
print(ideal[['Avg_Daily_Usage_Hours', 'Sleep_Hours_Per_Night', 'Mental_Health_Score', 'Affects_Academic_Performance']])